type Bindings = Env;
type Session = { user_id: number; username: string; email: string; role: string; expires_at: string; is_active: number };

const SESSION_DAYS = 7;
const PBKDF2_ITERATIONS = 120000;
const MAX_BODY = 256 * 1024;
const SETTINGS = new Set(['site_title','site_description','site_logo','site_favicon','contact_email','social_facebook','social_twitter','social_instagram','homepage_html','footer_html','meta_keywords','google_analytics_id']);

const headers = () => ({
  'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'strict-origin-when-cross-origin',
  'Strict-Transport-Security':'max-age=31536000; includeSubDomains','Permissions-Policy':'camera=(), microphone=(), geolocation=()'
});
const json = (data: unknown, status=200, extra: Record<string,string>={}) => new Response(JSON.stringify(data), { status, headers:{'content-type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers(),...extra} });
const fail = (message:string,status=400) => json({error:message},status);
const str = (v:unknown,max=5000) => typeof v==='string' ? v.trim().slice(0,max) : '';
const integer = (v:unknown) => typeof v==='number' && Number.isInteger(v) ? v : typeof v==='string' && /^\d+$/.test(v) ? Number(v) : null;
const number = (v:unknown) => { const n=typeof v==='number'?v:typeof v==='string'?Number(v):NaN; return Number.isFinite(n)?n:null; };

async function input(req:Request){
  const len=Number(req.headers.get('content-length')||0); if(len>MAX_BODY)return null;
  try{const v=await req.json();return v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,any>:null;}catch{return null;}
}
async function digest(v:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
function equal(a:string,b:string){if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;}
function hexBytes(v:string){const a=new Uint8Array(v.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(v.slice(i*2,i*2+2),16);return a;}
async function passwordHash(password:string,saltHex?:string){
  const salt=saltHex?hexBytes(saltHex):crypto.getRandomValues(new Uint8Array(16));
  const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);
  const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:PBKDF2_ITERATIONS,hash:'SHA-256'},key,256);
  return {salt:[...salt].map(x=>x.toString(16).padStart(2,'0')).join(''),hash:[...new Uint8Array(bits)].map(x=>x.toString(16).padStart(2,'0')).join('')};
}
function cookie(name:string,value:string,maxAge:number){return `${name}=${encodeURIComponent(value)}; Path=/; Secure; HttpOnly; SameSite=Strict; Max-Age=${maxAge}`;}
function getCookie(req:Request,name:string){const s=req.headers.get('Cookie')||'';const p=s.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='));return p?decodeURIComponent(p.slice(name.length+1)):null;}
function sameOrigin(req:Request){const o=req.headers.get('Origin');if(!o)return true;try{return o===new URL(req.url).origin}catch{return false;}}

async function session(req:Request,env:Bindings):Promise<Session|null>{
  const token=getCookie(req,'bn_session');if(!token||token.length<32)return null;
  return await env.DB.prepare(`SELECT s.user_id,s.expires_at,u.username,u.email,u.is_active,COALESCE(r.role,'user') role FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN user_roles r ON r.user_id=u.id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.is_active=1 LIMIT 1`).bind(await digest(token)).first<Session>();
}
async function admin(req:Request,env:Bindings){const s=await session(req,env);if(!s)return fail('Authentication required',401);if(s.role!=='admin')return fail('Admin access required',403);if(!sameOrigin(req))return fail('Invalid request origin',403);return s;}
async function newSession(env:Bindings,userId:number){
  const token=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');
  await env.DB.prepare("DELETE FROM sessions WHERE expires_at<=CURRENT_TIMESTAMP").run();
  await env.DB.prepare(`INSERT INTO sessions(user_id,token_hash,csrf_token,expires_at) VALUES(?,?,?,datetime('now','+${SESSION_DAYS} days'))`).bind(userId,await digest(token),crypto.randomUUID().replaceAll('-','')).run();
  return token;
}

async function auth(req:Request,env:Bindings,path:string){
  if(path==='/api/auth/register'&&req.method==='POST'){
    if(!sameOrigin(req))return fail('Invalid request origin',403);const i=await input(req);if(!i)return fail('Invalid JSON');
    const username=str(i.username,40),email=str(i.email,160).toLowerCase(),password=typeof i.password==='string'?i.password:'';
    if(!/^[a-zA-Z0-9_.-]{3,40}$/.test(username)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||password.length<8||password.length>200)return fail('Invalid registration data');
    const count=Number((await env.DB.prepare('SELECT COUNT(*) count FROM users').first<any>())?.count||0);const h=await passwordHash(password);
    try{const r=await env.DB.prepare('INSERT INTO users(username,email,password_hash,password_salt) VALUES(?,?,?,?)').bind(username,email,h.hash,h.salt).run();const id=Number(r.meta.last_row_id);await env.DB.prepare('INSERT INTO user_roles(user_id,role) VALUES(?,?)').bind(id,count===0?'admin':'user').run();const token=await newSession(env,id);return json({ok:true,user:{id,username,email,role:count===0?'admin':'user'}},201,{'Set-Cookie':cookie('bn_session',token,SESSION_DAYS*86400)});}catch{return fail('Username or email already exists',409);}
  }
  if(path==='/api/auth/login'&&req.method==='POST'){
    if(!sameOrigin(req))return fail('Invalid request origin',403);const i=await input(req);if(!i)return fail('Invalid JSON');const username=str(i.username,40),password=typeof i.password==='string'?i.password:'';
    const u=await env.DB.prepare(`SELECT u.*,COALESCE(r.role,'user') role FROM users u LEFT JOIN user_roles r ON r.user_id=u.id WHERE u.username=? COLLATE NOCASE LIMIT 1`).bind(username).first<any>();
    if(!u||!u.is_active)return fail('Invalid username or password',401);const h=await passwordHash(password,u.password_salt);if(!equal(h.hash,u.password_hash))return fail('Invalid username or password',401);
    const token=await newSession(env,u.id);return json({ok:true,user:{id:u.id,username:u.username,email:u.email,role:u.role}},200,{'Set-Cookie':cookie('bn_session',token,SESSION_DAYS*86400)});
  }
  if(path==='/api/auth/me'&&req.method==='GET'){const s=await session(req,env);if(!s)return fail('Not authenticated',401);return json({user:{id:s.user_id,username:s.username,email:s.email,role:s.role}});}
  if(path==='/api/auth/logout'&&req.method==='POST'){if(!sameOrigin(req))return fail('Invalid request origin',403);const t=getCookie(req,'bn_session');if(t)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(t)).run();return json({ok:true},200,{'Set-Cookie':cookie('bn_session','',0)});}
  return fail('Not found',404);
}

async function publicApi(req:Request,env:Bindings,path:string){
  if(req.method!=='GET')return fail('Method not allowed',405);
  if(path==='/api/settings'){const r=await env.DB.prepare('SELECT key,value FROM settings').all<any>();const settings:Record<string,string>={};for(const x of r.results||[])settings[x.key]=x.value;return json({settings},200,{'Cache-Control':'public,max-age=60'});}
  if(path==='/api/categories'){const r=await env.DB.prepare('SELECT id,name,slug,description,parent_id,is_active FROM categories WHERE is_active=1 ORDER BY name COLLATE NOCASE').all();return json({categories:r.results||[]},200,{'Cache-Control':'public,max-age=60'});}
  if(path.startsWith('/api/categories/')){const slug=decodeURIComponent(path.slice(15));const c=await env.DB.prepare('SELECT id,name,slug,description,parent_id,is_active FROM categories WHERE slug=? COLLATE NOCASE AND is_active=1').bind(slug).first<any>();if(!c)return fail('Category not found',404);const r=await env.DB.prepare('SELECT id,name,description,price,image_url,affiliate_url,category_id,is_active,created_at FROM products WHERE category_id=? AND is_active=1 ORDER BY created_at DESC LIMIT 100').bind(c.id).all();return json({category:c,products:r.results||[]},200,{'Cache-Control':'public,max-age=60'});}
  if(path==='/api/products'){const r=await env.DB.prepare('SELECT id,name,description,price,image_url,affiliate_url,category_id,is_active,created_at FROM products WHERE is_active=1 ORDER BY created_at DESC LIMIT 100').all();return json({products:r.results||[]},200,{'Cache-Control':'public,max-age=60'});}
  if(path.startsWith('/api/products/')){const id=integer(path.slice(14));if(id===null)return fail('Invalid product id');const p=await env.DB.prepare('SELECT p.*,c.name category_name FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.id=? AND p.is_active=1').bind(id).first<any>();if(!p)return fail('Product not found',404);const r=await env.DB.prepare("SELECT id,user_name,rating,comment,created_at FROM reviews WHERE product_id=? AND status='approved' ORDER BY created_at DESC LIMIT 50").bind(id).all();return json({product:p,reviews:r.results||[]},200,{'Cache-Control':'public,max-age=60'});}
  return fail('Not found',404);
}

async function adminApi(req:Request,env:Bindings,path:string){
  const a=await admin(req,env);if(a instanceof Response)return a;
  if(path==='/api/admin/products'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM products ORDER BY created_at DESC').all();return json({products:r.results||[]});}
  if(path==='/api/admin/products'&&req.method==='POST'){const i=await input(req);if(!i)return fail('Invalid JSON');const p=number(i.price),c=i.category_id?integer(i.category_id):null;if(!str(i.name,200)||p===null||p<0||(i.category_id&&c===null))return fail('Invalid product data');const r=await env.DB.prepare('INSERT INTO products(name,description,price,image_url,affiliate_url,category_id,is_active) VALUES(?,?,?,?,?,?,?)').bind(str(i.name,200),str(i.description,10000),p,str(i.image_url,2000),str(i.affiliate_url,2000),c,i.is_active?1:0).run();return json({id:r.meta.last_row_id},201);}
  let m=path.match(/^\/api\/admin\/products\/(\d+)$/);if(m){const id=Number(m[1]);if(req.method==='PUT'){const i=await input(req);if(!i)return fail('Invalid JSON');const e=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first<any>();if(!e)return fail('Product not found',404);const p=i.price===undefined?e.price:number(i.price),c=i.category_id===undefined?e.category_id:(i.category_id?integer(i.category_id):null);if(p===null||p<0||(i.category_id&&c===null))return fail('Invalid product data');await env.DB.prepare('UPDATE products SET name=?,description=?,price=?,image_url=?,affiliate_url=?,category_id=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(i.name===undefined?e.name:str(i.name,200),i.description===undefined?e.description:str(i.description,10000),p,i.image_url===undefined?e.image_url:str(i.image_url,2000),i.affiliate_url===undefined?e.affiliate_url:str(i.affiliate_url,2000),c,i.is_active===undefined?e.is_active:(i.is_active?1:0),id).run();return json({ok:true});}if(req.method==='DELETE'){await env.DB.prepare('DELETE FROM products WHERE id=?').bind(id).run();return json({ok:true});}}

  if(path==='/api/admin/categories'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM categories ORDER BY name COLLATE NOCASE').all();return json({categories:r.results||[]});}
  if(path==='/api/admin/categories'&&req.method==='POST'){const i=await input(req);if(!i)return fail('Invalid JSON');const name=str(i.name,160),slug=str(i.slug,160).toLowerCase(),parent=i.parent_id?integer(i.parent_id):null;if(!name||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))return fail('Invalid category data');try{const r=await env.DB.prepare('INSERT INTO categories(name,slug,description,parent_id,is_active) VALUES(?,?,?,?,?)').bind(name,slug,str(i.description,5000),parent,i.is_active?1:0).run();return json({id:r.meta.last_row_id},201);}catch{return fail('Category slug already exists',409);}}
  m=path.match(/^\/api\/admin\/categories\/(\d+)$/);if(m){const id=Number(m[1]);if(req.method==='PUT'){const i=await input(req);if(!i)return fail('Invalid JSON');const e=await env.DB.prepare('SELECT * FROM categories WHERE id=?').bind(id).first<any>();if(!e)return fail('Category not found',404);const slug=i.slug===undefined?e.slug:str(i.slug,160).toLowerCase(),parent=i.parent_id===undefined?e.parent_id:(i.parent_id?integer(i.parent_id):null);if(id===parent||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))return fail('Invalid category data');try{await env.DB.prepare('UPDATE categories SET name=?,slug=?,description=?,parent_id=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(i.name===undefined?e.name:str(i.name,160),slug,i.description===undefined?e.description:str(i.description,5000),parent,i.is_active===undefined?e.is_active:(i.is_active?1:0),id).run();return json({ok:true});}catch{return fail('Category slug already exists',409);}}if(req.method==='DELETE'){await env.DB.prepare('DELETE FROM categories WHERE id=?').bind(id).run();return json({ok:true});}}

  if(path==='/api/admin/reviews'&&req.method==='GET'){const r=await env.DB.prepare('SELECT r.*,p.name product_name FROM reviews r LEFT JOIN products p ON p.id=r.product_id ORDER BY r.created_at DESC').all();return json({reviews:r.results||[]});}
  m=path.match(/^\/api\/admin\/reviews\/(\d+)$/);if(m){const id=Number(m[1]);if(req.method==='PUT'){const i=await input(req);if(!i||!['pending','approved','rejected'].includes(i.status))return fail('Invalid review status');await env.DB.prepare('UPDATE reviews SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(i.status,id).run();return json({ok:true});}if(req.method==='DELETE'){await env.DB.prepare('DELETE FROM reviews WHERE id=?').bind(id).run();return json({ok:true});}}

  if(path==='/api/admin/coupons'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM coupons ORDER BY created_at DESC').all();return json({coupons:r.results||[]});}
  if(path==='/api/admin/coupons'&&req.method==='POST'){const i=await input(req);if(!i)return fail('Invalid JSON');const v=number(i.discount_value),min=number(i.min_purchase)??0,max=i.max_uses?integer(i.max_uses):null,type=i.discount_type==='fixed'?'fixed':'percentage';if(!str(i.code,40)||v===null||v<0||min<0||max!==null&&max<=0||type==='percentage'&&v>100)return fail('Invalid coupon data');try{const r=await env.DB.prepare('INSERT INTO coupons(code,description,discount_type,discount_value,min_purchase,max_uses,expires_at,is_active) VALUES(?,?,?,?,?,?,?,?)').bind(str(i.code,40).toUpperCase(),str(i.description,500),type,v,min,max,i.expires_at?str(i.expires_at,30):null,i.is_active?1:0).run();return json({id:r.meta.last_row_id},201);}catch{return fail('Coupon code already exists',409);}}
  m=path.match(/^\/api\/admin\/coupons\/(\d+)$/);if(m){const id=Number(m[1]);if(req.method==='PUT'){const i=await input(req);if(!i)return fail('Invalid JSON');const e=await env.DB.prepare('SELECT * FROM coupons WHERE id=?').bind(id).first<any>();if(!e)return fail('Coupon not found',404);const v=i.discount_value===undefined?e.discount_value:number(i.discount_value),min=i.min_purchase===undefined?e.min_purchase:number(i.min_purchase),max=i.max_uses===undefined?e.max_uses:(i.max_uses?integer(i.max_uses):null),type=i.discount_type===undefined?e.discount_type:(i.discount_type==='fixed'?'fixed':'percentage');if(v===null||v<0||min===null||min<0||max!==null&&max<=0||type==='percentage'&&v>100)return fail('Invalid coupon data');try{await env.DB.prepare('UPDATE coupons SET code=?,description=?,discount_type=?,discount_value=?,min_purchase=?,max_uses=?,expires_at=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(i.code===undefined?e.code:str(i.code,40).toUpperCase(),i.description===undefined?e.description:str(i.description,500),type,v,min,max,i.expires_at===undefined?e.expires_at:(i.expires_at?str(i.expires_at,30):null),i.is_active===undefined?e.is_active:(i.is_active?1:0),id).run();return json({ok:true});}catch{return fail('Coupon code already exists',409);}}if(req.method==='DELETE'){await env.DB.prepare('DELETE FROM coupons WHERE id=?').bind(id).run();return json({ok:true});}}

  if(path==='/api/admin/settings'&&req.method==='GET'){const r=await env.DB.prepare('SELECT key,value FROM settings ORDER BY key').all();return json({settings:r.results||[]});}
  if(path==='/api/admin/settings'&&req.method==='PUT'){const i=await input(req);if(!i||!i.settings||typeof i.settings!=='object')return fail('Invalid settings');const rows=Object.entries(i.settings).filter(([k])=>SETTINGS.has(k));for(const [k,v] of rows)await env.DB.prepare('INSERT INTO settings(key,value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=CURRENT_TIMESTAMP').bind(k,str(v,50000)).run();return json({ok:true});}

  if(path==='/api/admin/scripts'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM custom_scripts ORDER BY created_at DESC').all();return json({scripts:r.results||[]});}
  if(path==='/api/admin/scripts'&&req.method==='POST'){const i=await input(req);if(!i)return fail('Invalid JSON');if(!str(i.name,160)||!['javascript','css','html'].includes(i.type)||!['head','body_start','body_end'].includes(i.location)||!str(i.content,50000))return fail('Invalid script data');const r=await env.DB.prepare('INSERT INTO custom_scripts(name,type,content,location,is_active) VALUES(?,?,?,?,?)').bind(str(i.name,160),i.type,str(i.content,50000),i.location,i.is_active?1:0).run();return json({id:r.meta.last_row_id},201);}
  m=path.match(/^\/api\/admin\/scripts\/(\d+)$/);if(m){const id=Number(m[1]);if(req.method==='PUT'){const i=await input(req);if(!i)return fail('Invalid JSON');const e=await env.DB.prepare('SELECT * FROM custom_scripts WHERE id=?').bind(id).first<any>();if(!e)return fail('Script not found',404);const type=i.type===undefined?e.type:i.type,loc=i.location===undefined?e.location:i.location;if(!['javascript','css','html'].includes(type)||!['head','body_start','body_end'].includes(loc))return fail('Invalid script data');await env.DB.prepare('UPDATE custom_scripts SET name=?,type=?,content=?,location=?,is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(i.name===undefined?e.name:str(i.name,160),type,i.content===undefined?e.content:str(i.content,50000),loc,i.is_active===undefined?e.is_active:(i.is_active?1:0),id).run();return json({ok:true});}if(req.method==='DELETE'){await env.DB.prepare('DELETE FROM custom_scripts WHERE id=?').bind(id).run();return json({ok:true});}}

  if(path==='/api/admin/users'&&req.method==='GET'){const r=await env.DB.prepare('SELECT id,username,email,is_active,created_at FROM users ORDER BY created_at DESC').all();return json({users:r.results||[]});}
  if(path==='/api/admin/user-roles'&&req.method==='GET'){const r=await env.DB.prepare('SELECT user_id,role FROM user_roles').all();return json({roles:r.results||[]});}
  if(path==='/api/admin/users'&&req.method==='POST'){const i=await input(req);if(!i)return fail('Invalid JSON');const u=str(i.username,40),e=str(i.email,160).toLowerCase(),p=typeof i.password==='string'?i.password:'';if(!/^[a-zA-Z0-9_.-]{3,40}$/.test(u)||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)||p.length<8||p.length>200)return fail('Invalid user data');const h=await passwordHash(p);try{const r=await env.DB.prepare('INSERT INTO users(username,email,password_hash,password_salt) VALUES(?,?,?,?)').bind(u,e,h.hash,h.salt).run();const id=Number(r.meta.last_row_id);await env.DB.prepare('INSERT INTO user_roles(user_id,role) VALUES(?,?)').bind(id,['user','moderator','admin'].includes(i.role)?i.role:'user').run();return json({id},201);}catch{return fail('Username or email already exists',409);}}
  m=path.match(/^\/api\/admin\/users\/(\d+)$/);if(m){const id=Number(m[1]);if(req.method==='PUT'){const i=await input(req);if(!i)return fail('Invalid JSON');if(id===a.user_id&&i.is_active===0)return fail('You cannot deactivate yourself');await env.DB.prepare('UPDATE users SET is_active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(i.is_active?1:0,id).run();return json({ok:true});}if(req.method==='DELETE'){if(id===a.user_id)return fail('You cannot delete yourself');await env.DB.prepare('DELETE FROM users WHERE id=?').bind(id).run();return json({ok:true});}}
  m=path.match(/^\/api\/admin\/user-roles\/(\d+)$/);if(m&&req.method==='PUT'){const id=Number(m[1]),i=await input(req);if(!i||!['user','moderator','admin'].includes(i.role))return fail('Invalid role');if(id===a.user_id&&i.role!=='admin')return fail('You cannot remove your own admin role');await env.DB.prepare('INSERT INTO user_roles(user_id,role) VALUES(?,?) ON CONFLICT(user_id) DO UPDATE SET role=excluded.role').bind(id,i.role).run();return json({ok:true});}

  if(path==='/api/admin/analytics/stats'&&req.method==='GET'){const [p,u,r,c,co]=await Promise.all([env.DB.prepare('SELECT COUNT(*) count FROM products').first<any>(),env.DB.prepare('SELECT COUNT(*) count FROM users').first<any>(),env.DB.prepare("SELECT COUNT(*) count FROM reviews WHERE status='pending'").first<any>(),env.DB.prepare('SELECT COUNT(*) count FROM categories').first<any>(),env.DB.prepare('SELECT COUNT(*) count FROM coupons WHERE is_active=1').first<any>()]);return json({stats:{products:Number(p?.count||0),users:Number(u?.count||0),pendingReviews:Number(r?.count||0),categories:Number(c?.count||0),activeCoupons:Number(co?.count||0)}});}
  if(path==='/api/admin/analytics'&&req.method==='GET'){const r=await env.DB.prepare("SELECT substr(created_at,1,10) date,COUNT(*) events FROM analytics_events GROUP BY substr(created_at,1,10) ORDER BY date DESC LIMIT 30").all();return json({analytics:r.results||[]});}
  return fail('Not found',404);
}

export default { async fetch(req:Request,env:Bindings){const url=new URL(req.url);try{if(url.pathname.startsWith('/api/auth/'))return await auth(req,env,url.pathname);if(url.pathname.startsWith('/api/admin/'))return await adminApi(req,env,url.pathname);if(url.pathname.startsWith('/api/'))return await publicApi(req,env,url.pathname);let asset=await env.ASSETS.fetch(req);if(asset.status===404&&req.method==='GET')asset=await env.ASSETS.fetch(new Request(new URL('/index.html',req.url),req));const res=new Response(asset.body,asset);res.headers.set('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https://imagedelivery.net; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests");for(const [k,v] of Object.entries(headers()))res.headers.set(k,v);return res;}catch(e){console.error(e);return fail('Internal server error',500);}}} satisfies ExportedHandler<Bindings>;
