import { Vehicle, VehicleCuratedCollection } from './types';

export const CURATED_COLLECTIONS: VehicleCuratedCollection[] = [
  {
    id: 'cheapest-ev',
    slug: 'cheapest-ev',
    title: 'Cheapest Electric Cars in Nepal',
    subtitle: 'Under 45 Lakhs with 0% EMI and Low Maintenance',
    icon: '⚡',
    filter_fuel: 'ev',
    max_price: 4500000,
    description: 'Affordable, reliable city electric cars requiring just 20% downpayment per Nepal Rastra Bank guidelines.'
  },
  {
    id: 'high-ground-clearance',
    slug: 'high-ground-clearance',
    title: 'Pothole-Proof SUVs (>185mm Ground Clearance)',
    subtitle: 'High clearance built for Nepal highway potholes and monsoon roads',
    icon: '🏔️',
    min_ground_clearance: 185,
    description: 'Vehicles with generous underbody clearance engineered to conquer Mugling road, speed breakers, and unpaved mountain highways.'
  },
  {
    id: 'long-range-ev',
    slug: 'long-range-ev',
    title: 'Long-Range Highway Cruisers (400km+ Range)',
    subtitle: 'Drive Kathmandu to Pokhara without intermediate DC charging anxiety',
    icon: '🔋',
    filter_fuel: 'ev',
    min_range: 400,
    description: 'High-density battery packs capable of inter-city highway trips across Nepal on a single full charge.'
  },
  {
    id: 'electric-two-wheelers',
    slug: 'electric-two-wheelers',
    title: 'Top Electric Scooters & Bikes',
    subtitle: 'Zero petrol bill for daily valley traffic commutes',
    icon: '🛵',
    filter_fuel: 'ev',
    filter_type: 'scooter',
    description: 'Smart connected electric two-wheelers with removable or fast-charging batteries and touchscreens.'
  },
  {
    id: 'luxury-ev',
    slug: 'luxury-ev',
    title: 'Premium Flagship Electric Vehicles',
    subtitle: 'Top-tier luxury, frameless doors, and supercar acceleration',
    icon: '👑',
    filter_fuel: 'ev',
    min_price: 6000000,
    description: 'Executive electric saloons and futuristic fastbacks with ADAS Level 2 safety and ultra-luxurious cabins.'
  }
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 1,
    name: 'BYD Atto 3 Superior',
    slug: 'byd-atto-3-superior',
    brand: 'BYD',
    vehicle_type: 'suv',
    fuel_type: 'ev',
    price_npr: 6680000,
    original_price_npr: 6850000,
    badge: '🇳🇵 #1 Selling EV in Nepal',
    image_url: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=900&auto=format&fit=crop&q=80',
    gallery_images: [
      'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=900&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1563720223185-11003d516935?w=900&auto=format&fit=crop&q=80'
    ],
    distributor_nepal: 'Cimex Inc. Pvt. Ltd.',
    showroom_location: 'Naxal, Radhe Radhe & Pokhara Showrooms',
    warranty_battery: '8 Years / 160,000 km (Blade Battery)',
    warranty_vehicle: '6 Years / 150,000 km Whole Vehicle',
    battery_capacity_kwh: 60.48,
    range_km: 420,
    motor_power_kw: 150,
    motor_torque_nm: 310,
    top_speed_kmh: 160,
    acceleration_0_100: 7.3,
    charging_time_dc_fast: '45 mins (0-80% on 80kW DC Fast Charger)',
    charging_time_ac_home: '9.5 hours on 7kW AC Home Wallbox',
    charging_port: 'CCS Type 2 (Standard in Nepal)',
    ground_clearance_mm: 175,
    seating_capacity: 5,
    boot_space_liters: 440,
    airbags_count: 7,
    ncap_rating: '5-Star Euro NCAP',
    annual_road_tax_npr: 15000,
    verdict_nepal: 'Nepal\'s reigning king of electric SUVs. The Blade Battery has proven virtually indestructible in Nepal summers, with expansive fast charging along BP Highway and Prithvi Highway.',
    pros: [
      'Ultra-safe Blade Battery technology with zero puncture fire risk',
      'Spacious 420km real-world range easily handles Kathmandu-Pokhara without charging',
      'Highest resale liquidity of any vehicle brand in Nepal today',
      'Rotating 12.8-inch touchscreen with Apple CarPlay and Android Auto'
    ],
    cons: [
      'Interior guitar-string door pockets may divide opinion',
      '175mm ground clearance requires caution on steep rural humps'
    ],
    rating: 4.9,
    score_overall: 9.6,
    scores: {
      range_efficiency: 9.6,
      performance: 9.3,
      ground_clearance: 8.8,
      nepal_value: 9.8,
      charging_network: 9.7
    },
    auto_loan_min_downpayment_npr: 1336000, // 20% downpayment per NRB
    auto_loan_est_monthly_emi: 83200, // 80% loan over 7 yrs @ 10%
    test_drive_url: 'https://cimex.com.np',
    brochure_url: 'https://cimex.com.np/atto3',
    is_featured: 1,
    is_active: 1
  },
  {
    id: 2,
    name: 'Tata Nexon EV Empowered Plus',
    slug: 'tata-nexon-ev-empowered-plus',
    brand: 'Tata',
    vehicle_type: 'suv',
    fuel_type: 'ev',
    price_npr: 4699000,
    original_price_npr: 4899000,
    badge: '🏔️ Best High Clearance EV',
    image_url: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'Sipradi Trading Pvt. Ltd.',
    showroom_location: 'Thapathali, Naikap, Biratnagar, Butwal, Nepalgunj',
    warranty_battery: '8 Years / 160,000 km IP67 Pack',
    warranty_vehicle: '3 Years / 125,000 km Standard Warranty',
    battery_capacity_kwh: 40.5,
    range_km: 465,
    motor_power_kw: 105,
    motor_torque_nm: 215,
    top_speed_kmh: 150,
    acceleration_0_100: 8.9,
    charging_time_dc_fast: '56 mins (10-80% on 50kW DC Charger)',
    charging_time_ac_home: '6.5 hours on 7.2kW AC Wallbox',
    charging_port: 'CCS Type 2',
    ground_clearance_mm: 190,
    seating_capacity: 5,
    boot_space_liters: 350,
    airbags_count: 6,
    ncap_rating: '5-Star Bharat NCAP',
    annual_road_tax_npr: 15000,
    verdict_nepal: 'Unmatched 190mm ground clearance and Sipradi\'s 32+ service centers across Nepal make the Nexon EV the safest bet for rough roads, monsoon flooding, and rural highway transit.',
    pros: [
      'Massive 190mm ground clearance clears all Kathmandu potholes and monsoon ruts',
      'Sipradi network ensures spare parts and technicians in every major town',
      'V2V and V2L charging capability allows powering camping equipment or emergency jumps',
      'Refined gen-2 cabin with 10.25-inch cinematic touchscreen and ventilated seats'
    ],
    cons: [
      'Cabin width slightly narrower than BYD Atto 3',
      'Real-world hill range closer to 330km under aggressive AC usage'
    ],
    rating: 4.8,
    score_overall: 9.3,
    scores: {
      range_efficiency: 9.1,
      performance: 8.9,
      ground_clearance: 9.9,
      nepal_value: 9.5,
      charging_network: 9.8
    },
    auto_loan_min_downpayment_npr: 939800, // 20% down
    auto_loan_est_monthly_emi: 58500,
    test_drive_url: 'https://sipradi.com.np',
    brochure_url: 'https://sipradi.com.np/nexon-ev',
    is_featured: 1,
    is_active: 1
  },
  {
    id: 3,
    name: 'Tata Tiago EV Long Range',
    slug: 'tata-tiago-ev-long-range',
    brand: 'Tata',
    vehicle_type: 'hatchback',
    fuel_type: 'ev',
    price_npr: 2749000,
    original_price_npr: 2890000,
    badge: '💰 Most Affordable EV Car',
    image_url: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'Sipradi Trading Pvt. Ltd.',
    showroom_location: 'All Authorized Tata Showrooms in Nepal',
    warranty_battery: '8 Years / 160,000 km Pack',
    warranty_vehicle: '3 Years / 125,000 km',
    battery_capacity_kwh: 24.0,
    range_km: 315,
    motor_power_kw: 55,
    motor_torque_nm: 114,
    top_speed_kmh: 120,
    acceleration_0_100: 12.0,
    charging_time_dc_fast: '57 mins (10-80% on 25kW DC Fast)',
    charging_time_ac_home: '3.6 hours on 7.2kW AC Wallbox',
    charging_port: 'CCS Type 2',
    ground_clearance_mm: 170,
    seating_capacity: 5,
    boot_space_liters: 240,
    airbags_count: 2,
    ncap_rating: '4-Star Global NCAP',
    annual_road_tax_npr: 10000,
    verdict_nepal: 'The undisputed value champion. For under 28 Lakhs with Rs. 5.5 Lakhs down payment, it eliminates petrol expense forever with running cost under Rs. 1.2 per km.',
    pros: [
      'Sub-28 Lakhs price tag makes 4-wheel ownership accessible for Nepali middle class',
      'Tiny turning radius is effortless for narrow Patan, Ason, and Bhaktapur alleys',
      'Regenerative braking with 4 levels recovers energy descending from Nagarkot / Chandragiri'
    ],
    cons: [
      'Compact rear boot (240L) requires folding seats for large luggage bags',
      'Highway top speed limited to 120 km/h'
    ],
    rating: 4.7,
    score_overall: 9.1,
    scores: {
      range_efficiency: 8.8,
      performance: 8.0,
      ground_clearance: 8.6,
      nepal_value: 9.9,
      charging_network: 9.5
    },
    auto_loan_min_downpayment_npr: 549800, // 20% down
    auto_loan_est_monthly_emi: 34200,
    test_drive_url: 'https://sipradi.com.np',
    is_featured: 1,
    is_active: 1
  },
  {
    id: 4,
    name: 'BYD Dolphin Dynamic',
    slug: 'byd-dolphin-dynamic',
    brand: 'BYD',
    vehicle_type: 'hatchback',
    fuel_type: 'ev',
    price_npr: 4115000,
    original_price_npr: 4199000,
    badge: '⚡ Smart City Hatchback',
    image_url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'Cimex Inc. Pvt. Ltd.',
    showroom_location: 'Naxal, Kathmandu',
    warranty_battery: '8 Years / 160,000 km Blade Battery',
    warranty_vehicle: '6 Years / 150,000 km',
    battery_capacity_kwh: 44.9,
    range_km: 340,
    motor_power_kw: 70,
    motor_torque_nm: 180,
    top_speed_kmh: 150,
    acceleration_0_100: 10.9,
    charging_time_dc_fast: '38 mins (30-80% on 60kW DC)',
    charging_time_ac_home: '6.5 hours on 7kW AC',
    charging_port: 'CCS Type 2',
    ground_clearance_mm: 175,
    seating_capacity: 5,
    boot_space_liters: 345,
    airbags_count: 6,
    ncap_rating: '5-Star Euro NCAP',
    annual_road_tax_npr: 10000,
    verdict_nepal: 'Ocean aesthetics, ultra-plush suspension, and a flat rear floor make this the premier choice for tech-forward young professionals and daily urban drivers.',
    pros: [
      'Extremely comfortable, supple suspension glides over road ripples',
      'Flat rear floor gives incredible legroom for 3 rear passengers',
      'Built on dedicated e-Platform 3.0 with high thermal efficiency heat pump'
    ],
    cons: [
      'Front wheel spin can occur if launching hard on wet Kathmandu roads'
    ],
    rating: 4.8,
    score_overall: 9.4,
    scores: {
      range_efficiency: 9.3,
      performance: 8.8,
      ground_clearance: 8.8,
      nepal_value: 9.5,
      charging_network: 9.7
    },
    auto_loan_min_downpayment_npr: 823000,
    auto_loan_est_monthly_emi: 51200,
    test_drive_url: 'https://cimex.com.np',
    is_featured: 0,
    is_active: 1
  },
  {
    id: 5,
    name: 'Deepal S07 Luxury EV SUV',
    slug: 'deepal-s07-luxury-ev-suv',
    brand: 'Deepal',
    vehicle_type: 'suv',
    fuel_type: 'ev',
    price_npr: 7199000,
    original_price_npr: 7499000,
    badge: '👑 Futuristic Flagship',
    image_url: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'MAW Vriddhi Commercial Vehicles',
    showroom_location: 'Bhatbhateni, Naxal, Kathmandu',
    warranty_battery: '8 Years / 160,000 km Golden Bell Battery',
    warranty_vehicle: '5 Years / 120,000 km Whole Vehicle',
    battery_capacity_kwh: 66.8,
    range_km: 530,
    motor_power_kw: 160,
    motor_torque_nm: 320,
    top_speed_kmh: 180,
    acceleration_0_100: 6.9,
    charging_time_dc_fast: '35 mins (30-80% on 100kW DC)',
    charging_time_ac_home: '9 hours on 7kW AC',
    charging_port: 'CCS Type 2',
    ground_clearance_mm: 175,
    seating_capacity: 5,
    boot_space_liters: 445,
    airbags_count: 8,
    ncap_rating: '5-Star C-NCAP',
    annual_road_tax_npr: 15000,
    verdict_nepal: 'The most head-turning electric vehicle in Nepal right now. Frameless doors, interactive front grille lighting, 15.6" sunflower rotating screen, and AR Heads-Up Display.',
    pros: [
      'Breathtaking supercar-inspired styling with frameless doors and hidden flush handles',
      'Massive 530km range allows roundtrip Kathmandu to Chitwan with ease',
      'Zero-gravity ventilated front seats with massage functions'
    ],
    cons: [
      'Ultra-wide body (1930mm) takes getting used to on narrow alleys'
    ],
    rating: 4.9,
    score_overall: 9.7,
    scores: {
      range_efficiency: 9.8,
      performance: 9.6,
      ground_clearance: 8.7,
      nepal_value: 9.2,
      charging_network: 9.4
    },
    auto_loan_min_downpayment_npr: 1439800,
    auto_loan_est_monthly_emi: 89600,
    test_drive_url: 'https://mawnepal.com',
    is_featured: 1,
    is_active: 1
  },
  {
    id: 6,
    name: 'MG ZS EV Long Range',
    slug: 'mg-zs-ev-long-range',
    brand: 'MG',
    vehicle_type: 'suv',
    fuel_type: 'ev',
    price_npr: 5299000,
    original_price_npr: 5499000,
    badge: '🔥 Hot Deal',
    image_url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'Paramount Motors Pvt. Ltd.',
    showroom_location: 'Naxal, Biratnagar, Narayangadh, Pokhara',
    warranty_battery: '8 Years / 150,000 km',
    warranty_vehicle: '5 Years / 100,000 km',
    battery_capacity_kwh: 51.1,
    range_km: 320,
    motor_power_kw: 99,
    motor_torque_nm: 280,
    top_speed_kmh: 175,
    acceleration_0_100: 8.6,
    charging_time_dc_fast: '40 mins (0-80% on 50kW DC)',
    charging_time_ac_home: '7.5 hours on 7kW AC',
    charging_port: 'CCS Type 2',
    ground_clearance_mm: 177,
    seating_capacity: 5,
    boot_space_liters: 448,
    airbags_count: 6,
    ncap_rating: '5-Star Euro NCAP',
    annual_road_tax_npr: 15000,
    verdict_nepal: 'A pioneer of the EV revolution in Nepal. Features a panoramic sunroof, PM2.5 air filter for Kathmandu dust, and reliable Paramount Motors aftersales service.',
    pros: [
      'Huge panoramic glass roof creates an airy, luxurious cabin atmosphere',
      'Built-in PM2.5 air purifier essential for winter smog in Kathmandu',
      'Very strong low-end torque for overtaking on mountain inclines'
    ],
    cons: [
      '320km range is slightly behind newer 2026 competitors'
    ],
    rating: 4.6,
    score_overall: 9.0,
    scores: {
      range_efficiency: 8.6,
      performance: 9.0,
      ground_clearance: 8.9,
      nepal_value: 9.1,
      charging_network: 9.3
    },
    auto_loan_min_downpayment_npr: 1059800,
    auto_loan_est_monthly_emi: 66000,
    test_drive_url: 'https://mgmotors.com.np',
    is_featured: 0,
    is_active: 1
  },
  {
    id: 7,
    name: 'Suzuki Jimny Alpha 4x4 AllGrip Pro',
    slug: 'suzuki-jimny-alpha-4x4',
    brand: 'Suzuki',
    vehicle_type: 'suv',
    fuel_type: 'petrol',
    price_npr: 5999000,
    original_price_npr: 6150000,
    badge: '🏔️ Mountain Offroad Icon',
    image_url: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'CG Motocorp Nepal',
    showroom_location: 'Thapathali, Pokhara, Butwal & Nationwide',
    warranty_vehicle: '3 Years / 60,000 km',
    engine_displacement_cc: 1462,
    transmission: '5-Speed Manual with 4WD Low Range',
    fuel_economy_kmpl: 16.94,
    fuel_tank_liters: 40,
    ground_clearance_mm: 210,
    seating_capacity: 4,
    boot_space_liters: 208,
    airbags_count: 6,
    ncap_rating: '3-Star Euro NCAP',
    annual_road_tax_npr: 35000,
    verdict_nepal: 'The ultimate ladder-frame 4x4 mountain conqueror for Upper Mustang, Rara, and Manang. 210mm clearance with true low-range gearbox.',
    pros: [
      'Unstoppable 210mm ground clearance and 4x4 low ratio transfer case',
      'Legendary ladder-frame durability proven across rugged Himalayan trails',
      'CG Motocorp service stations in all 77 districts with dirt-cheap spare parts'
    ],
    cons: [
      '50% downpayment required under NRB auto loan rules for petrol vehicles',
      'Firm ride quality on paved city asphalt'
    ],
    rating: 4.8,
    score_overall: 9.2,
    scores: {
      range_efficiency: 8.5,
      performance: 9.1,
      ground_clearance: 10.0,
      nepal_value: 9.0,
      charging_network: 8.0
    },
    auto_loan_min_downpayment_npr: 2999500, // 50% down per NRB
    auto_loan_est_monthly_emi: 46700, // on 50% loan
    test_drive_url: 'https://cgmaruti.com',
    is_featured: 0,
    is_active: 1
  },
  {
    id: 8,
    name: 'Ather 450X Gen 3 Smart Electric Scooter',
    slug: 'ather-450x-gen-3',
    brand: 'Ather',
    vehicle_type: 'scooter',
    fuel_type: 'ev',
    price_npr: 399000,
    original_price_npr: 415000,
    badge: '⚡ Smart Tech Two-Wheeler',
    image_url: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'Vaidya Energy Nepal',
    showroom_location: 'Tinkune, Kathmandu & Pokhara',
    warranty_battery: '5 Years / 60,000 km Battery Protection',
    warranty_vehicle: '3 Years Vehicle Warranty',
    battery_capacity_kwh: 3.7,
    range_km: 150,
    motor_power_kw: 6.4,
    motor_torque_nm: 26,
    top_speed_kmh: 90,
    acceleration_0_100: 3.3, // 0-40 in 3.3s
    charging_time_dc_fast: 'Ather Grid: 1.5 km/min fast charging',
    charging_time_ac_home: '5.5 hours from 5A home socket',
    ground_clearance_mm: 160,
    seating_capacity: 2,
    boot_space_liters: 22,
    annual_road_tax_npr: 3000,
    verdict_nepal: 'The undisputed benchmark for performance electric scooters in Nepal. Google Maps navigation on 7-inch Android dashboard, Warp mode, and auto-reverse assist.',
    pros: [
      'Warp Mode acceleration easily overtakes traffic on Ring Road',
      'True Google Maps integrated directly onto dashboard with 4G LTE SIM',
      'Zero maintenance with belt drive and aluminum space-frame chassis'
    ],
    cons: [
      'Premium pricing compared to entry level electric scooters'
    ],
    rating: 4.9,
    score_overall: 9.6,
    scores: {
      range_efficiency: 9.5,
      performance: 9.8,
      ground_clearance: 8.8,
      nepal_value: 9.3,
      charging_network: 9.2
    },
    auto_loan_min_downpayment_npr: 79800,
    auto_loan_est_monthly_emi: 4980,
    test_drive_url: 'https://atherenergy.com.np',
    is_featured: 1,
    is_active: 1
  },
  {
    id: 9,
    name: 'TVS iQube S Smart EV Scooter',
    slug: 'tvs-iqube-s',
    brand: 'TVS',
    vehicle_type: 'scooter',
    fuel_type: 'ev',
    price_npr: 299000,
    original_price_npr: 315000,
    badge: '🛵 Family Choice EV',
    image_url: 'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'Jagdamba Motors Pvt. Ltd.',
    showroom_location: 'All Authorized TVS Showrooms in Nepal',
    warranty_battery: '3 Years / 50,000 km',
    warranty_vehicle: '3 Years Warranty',
    battery_capacity_kwh: 3.04,
    range_km: 100,
    motor_power_kw: 4.4,
    motor_torque_nm: 33,
    top_speed_kmh: 78,
    acceleration_0_100: 4.2, // 0-40 in 4.2s
    charging_time_ac_home: '4.5 hours from 5A household wall socket',
    ground_clearance_mm: 157,
    seating_capacity: 2,
    boot_space_liters: 17,
    annual_road_tax_npr: 3000,
    verdict_nepal: 'Classic comfortable family scooter backed by TVS Jagdamba Motors\' nationwide network. Plush dual suspension, comfortable wide seat, and zero vibration.',
    pros: [
      'Very comfortable seating for pillion riders and elderly family members',
      'Nationwide service and mechanics available in every district of Nepal',
      'Super silent motor with regenerative braking'
    ],
    cons: [
      'Top speed capped at 78 km/h'
    ],
    rating: 4.7,
    score_overall: 9.1,
    scores: {
      range_efficiency: 9.0,
      performance: 8.6,
      ground_clearance: 8.6,
      nepal_value: 9.7,
      charging_network: 9.4
    },
    auto_loan_min_downpayment_npr: 59800,
    auto_loan_est_monthly_emi: 3720,
    test_drive_url: 'https://tvsnepal.com',
    is_featured: 0,
    is_active: 1
  },
  {
    id: 10,
    name: 'Omoda E5 Fastback Electric SUV',
    slug: 'omoda-e5-fastback',
    brand: 'Omoda',
    vehicle_type: 'suv',
    fuel_type: 'ev',
    price_npr: 6199000,
    original_price_npr: 6399000,
    badge: '⚡ Fastback Design',
    image_url: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?w=900&auto=format&fit=crop&q=80',
    distributor_nepal: 'SPG Automobiles Pvt. Ltd.',
    showroom_location: 'Uttardhoka, Lazimpat, Kathmandu',
    warranty_battery: '8 Years / 160,000 km LFP Pack',
    warranty_vehicle: '7 Years / 150,000 km',
    battery_capacity_kwh: 61.0,
    range_km: 430,
    motor_power_kw: 150,
    motor_torque_nm: 340,
    top_speed_kmh: 172,
    acceleration_0_100: 7.6,
    charging_time_dc_fast: '28 mins (30-80% on 80kW DC)',
    charging_time_ac_home: '8 hours on 9.9kW AC',
    charging_port: 'CCS Type 2',
    ground_clearance_mm: 180,
    seating_capacity: 5,
    boot_space_liters: 380,
    airbags_count: 7,
    ncap_rating: '5-Star Euro NCAP',
    annual_road_tax_npr: 15000,
    verdict_nepal: 'Sleek coupe-SUV silhouette with 180mm ground clearance. Sony 8-speaker audio, Level 2.5 ADAS active safety, and ultra-fast DC fast charging curve.',
    pros: [
      'Aggressive coupe styling turns heads on Kathmandu streets',
      'Excellent 180mm ground clearance clears high road bumps',
      'Fast 28-minute DC charging profile'
    ],
    cons: [
      'Sloping fastback roofline slightly reduces rear headroom for tall passengers'
    ],
    rating: 4.8,
    score_overall: 9.4,
    scores: {
      range_efficiency: 9.4,
      performance: 9.3,
      ground_clearance: 9.1,
      nepal_value: 9.3,
      charging_network: 9.2
    },
    auto_loan_min_downpayment_npr: 1239800,
    auto_loan_est_monthly_emi: 77200,
    test_drive_url: 'https://omodanepal.com',
    is_featured: 1,
    is_active: 1
  }
];

export const INITIAL_VEHICLE_INQUIRIES: any[] = [
  {
    id: 1,
    vehicle_id: 1,
    vehicle_name: 'BYD Atto 3 Superior',
    customer_name: 'Rohan Shrestha',
    customer_phone: '9841234567',
    customer_email: 'rohan.shrestha@gmail.com',
    city: 'Kathmandu',
    inquiry_type: 'test_drive',
    preferred_date: 'Tomorrow afternoon',
    message: 'Interested in exchanging my 2019 Hyundai Creta for the Atto 3. Please call back.',
    status: 'new',
    created_at: new Date(Date.now() - 3600000 * 4).toISOString()
  },
  {
    id: 2,
    vehicle_id: 2,
    vehicle_name: 'Tata Nexon EV Empowered Plus',
    customer_name: 'Anjali Sharma',
    customer_phone: '9856012345',
    customer_email: 'anjali.s@outlook.com',
    city: 'Pokhara',
    inquiry_type: 'bank_loan_assist',
    preferred_date: 'This Friday',
    message: 'Need quotation and Nabil Bank 20% downpayment auto loan breakdown for Pokhara delivery.',
    status: 'contacted',
    created_at: new Date(Date.now() - 3600000 * 22).toISOString()
  },
  {
    id: 3,
    vehicle_id: 8,
    vehicle_name: 'Ather 450X Gen 3',
    customer_name: 'Bikram Karki',
    customer_phone: '9801987654',
    customer_email: 'bikram.karki@yahoo.com',
    city: 'Lalitpur',
    inquiry_type: 'test_drive',
    preferred_date: 'Saturday morning',
    message: 'Want to test drive at Tinkune showroom.',
    status: 'test_drive_scheduled',
    created_at: new Date(Date.now() - 3600000 * 48).toISOString()
  }
];
